### ISSUE TITLE
doesn't compile in current debian

### ISSUE THREAD

**Issue by sub205** [ftnapps/FTNd#2]
Doesn't compile in Debian 12.9. Seems that the symbols are included multiple times (???)

I'm not deep enough into this to understand the entire problem or fix it.
Can someone advice?

/usr/bin/ld: ../lib/libdbase.a(dbcfg.o):(.bss+0xf8c8): multiple definition of `Diw'; zmmisc.o:(.bss+0x6108): first defined here
/usr/bin/ld: ../lib/libdbase.a(dbftn.o):(.bss+0x4560): multiple definition of `fidonet'; zmmisc.o:(.bss+0x1fc0): first defined here
/usr/bin/ld: ../lib/libdbase.a(dbftn.o):(.bss+0x12a0): multiple definition of `fidonet_fil'; binkp.o:(.bss+0x14e0): first defined here
/usr/bin/ld: ../lib/libdbase.a(dbftn.o):(.bss+0x4608): multiple definition of `fidonethdr'; zmmisc.o:(.bss+0x2068): first defined here
/usr/bin/ld: ../lib/libdbase.a(dbftn.o):(.bss+0x22a0): multiple definition of `fidonet_cnt'; binkp.o:(.bss+0x24e0): first defined here
/usr/bin/ld: ../lib/libdbase.a(dbftn.o):(.bss+0x0): multiple definition of `msgs_cnt'; binkp.o:(.bss+0x240): first defined here
/usr/bin/ld: ../lib/libdbase.a(dbftn.o):(.bss+0x20): multiple definition of `usr_fil'; binkp.o:(.bss+0x260): first defined here
/usr/bin/ld: ../lib/libdbase.a(dbftn.o):(.bss+0x1020): multiple definition of `usr_cnt'; binkp.o:(.bss+0x1260): first defined here
/usr/bin/ld: ../lib/libdbase.a(dbftn.o):(.bss+0x1040): multiple definition of `usr'; binkp.o:(.bss+0x1280): first defined here
/usr/bin/ld: ../lib/libdbase.a(dbftn.o):(.bss+0x1288): multiple definition of `usrhdr'; binkp.o:(.bss+0x14c8): first defined here
/usr/bin/ld: ../lib/libdbase.a(dbftn.o):(.bss+0x1290): multiple definition of `tic_cnt'; binkp.o:(.bss+0x14d0): first defined here
/usr/bin/ld: ../lib/libdbase.a(dbftn.o):(.bss+0x1294): multiple definition of `nodes_cnt'; binkp.o:(.bss+0x14d4): first defined here
/usr/bin/ld: ../lib/libdbase.a(dbftn.o):(.bss+0x22c0): multiple definition of `exitinfo'; binkp.o:(.bss+0x2540): first defined here

**Comment by johnsonjh** [comment]
I didn't check myself yet, but most likely workaround is to build with `-fcommon` added to CFLAGS.  If that does fix your problem, the real patch should be quite trivial.

**Comment by sub205** [comment]
Yes, that helped.
Maybe someone should update Makefile.global.in / configure.
